<?php

declare(strict_types=1);

use Fulcrum\Database\ConnectionInterface;
use Fulcrum\Database\Drivers\PostgresDriver;
use Fulcrum\Database\Migrations\Migration;

return new class implements Migration {
    public function up(ConnectionInterface $db): void
    {
        if ($db instanceof PostgresDriver) {
            $db->statement(
                'CREATE TABLE IF NOT EXISTS idempotency_keys (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    scope VARCHAR(64) NOT NULL,
                    idempotency_key VARCHAR(255) NOT NULL,
                    request_hash VARCHAR(64) NOT NULL,
                    response TEXT NOT NULL,
                    created_at INTEGER NOT NULL,
                    CONSTRAINT idempotency_keys_scope_key_unique UNIQUE (scope, idempotency_key)
                )'
            );
            $db->statement('CREATE INDEX IF NOT EXISTS idempotency_keys_created_at_index ON idempotency_keys (created_at)');

            return;
        }

        $db->statement(
            'CREATE TABLE IF NOT EXISTS idempotency_keys (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                scope VARCHAR(64) NOT NULL,
                idempotency_key VARCHAR(255) NOT NULL,
                request_hash VARCHAR(64) NOT NULL,
                response LONGTEXT NOT NULL,
                created_at INT NOT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY idempotency_keys_scope_key_unique (scope, idempotency_key),
                KEY idempotency_keys_created_at_index (created_at)
            )'
        );
    }

    public function down(ConnectionInterface $db): void
    {
        $db->statement('DROP TABLE IF EXISTS idempotency_keys');
    }
};
