<?php

declare(strict_types=1);

use Fulcrum\Database\ConnectionInterface;
use Fulcrum\Database\Drivers\PostgresDriver;
use Fulcrum\Database\Migrations\Migration;

return new class implements Migration {
    public function up(ConnectionInterface $db): void
    {
        if ($db instanceof PostgresDriver) {
            $db->statement(
                "CREATE TABLE IF NOT EXISTS jobs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    queue VARCHAR(255) NOT NULL DEFAULT 'default',
                    payload TEXT NOT NULL,
                    attempts INTEGER NOT NULL DEFAULT 0,
                    reserved_at INTEGER NULL DEFAULT NULL,
                    available_at INTEGER NOT NULL,
                    created_at INTEGER NOT NULL
                )"
            );
            $db->statement('CREATE INDEX IF NOT EXISTS jobs_queue_available_reserved_index ON jobs (queue, available_at, reserved_at)');

            return;
        }

        $db->statement(
            'CREATE TABLE IF NOT EXISTS jobs (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                queue VARCHAR(255) NOT NULL DEFAULT "default",
                payload LONGTEXT NOT NULL,
                attempts INT UNSIGNED NOT NULL DEFAULT 0,
                reserved_at INT NULL DEFAULT NULL,
                available_at INT NOT NULL,
                created_at INT NOT NULL,
                PRIMARY KEY (id),
                KEY jobs_queue_available_reserved_index (queue, available_at, reserved_at)
            )'
        );
    }

    public function down(ConnectionInterface $db): void
    {
        $db->statement('DROP TABLE IF EXISTS jobs');
    }
};
