<?php

declare(strict_types=1);

namespace Fulcrum\Tests\Integration;

use Fulcrum\Cache\CacheManager;
use Fulcrum\Database\DatabaseManager;
use Fulcrum\Database\ConnectionInterface;
use Fulcrum\Foundation\Config;
use Fulcrum\Database\Drivers\PostgresDriver;
use Fulcrum\Database\Migrations\MigrationRepository;
use Fulcrum\Database\Migrations\Migrator;
use Fulcrum\Queue\Job;
use Fulcrum\Queue\Queues\DatabaseQueue;
use RuntimeException;

final class IntegrationProbeJob implements Job
{
    public function __construct(public readonly string $name = 'probe') {}
}

function integrationConfig(): Config
{
    return new Config(__DIR__ . '/../../fixtures/no-config');
}

function envString(string $key, string $default): string
{
    $value = getenv($key);

    return is_string($value) && $value !== '' ? $value : $default;
}

function envInt(string $key, int $default): int
{
    $value = getenv($key);

    return is_string($value) && $value !== '' ? (int) $value : $default;
}

function migrationIntegrationTestsEnabled(): bool
{
    return getenv('FULCRUM_TEST_MIGRATIONS') === '1';
}

function relationalDatabase(string $driver): DatabaseManager
{
    $config = integrationConfig();
    $config->set('database.default', $driver);

    if ($driver === 'pgsql') {
        $config->set('database.connections.pgsql', [
            'driver' => 'pgsql',
            'host' => envString('FULCRUM_PGSQL_HOST', '127.0.0.1'),
            'port' => envInt('FULCRUM_PGSQL_PORT', 5432),
            'database' => envString('FULCRUM_PGSQL_DATABASE', 'fulcrum_ci'),
            'username' => envString('FULCRUM_PGSQL_USERNAME', 'fulcrum'),
            'password' => envString('FULCRUM_PGSQL_PASSWORD', 'secret'),
            'prefix' => '',
        ]);
    }

    if ($driver === 'mysql') {
        $config->set('database.connections.mysql', [
            'driver' => 'mysql',
            'host' => envString('FULCRUM_MYSQL_HOST', '127.0.0.1'),
            'port' => envInt('FULCRUM_MYSQL_PORT', 3306),
            'database' => envString('FULCRUM_MYSQL_DATABASE', 'fulcrum_ci'),
            'username' => envString('FULCRUM_MYSQL_USERNAME', 'fulcrum'),
            'password' => envString('FULCRUM_MYSQL_PASSWORD', 'secret'),
            'charset' => 'utf8mb4',
            'prefix' => '',
        ]);
    }

    return new DatabaseManager($config);
}

function exerciseRelationalDatabase(string $driver): void
{
    $db = relationalDatabase($driver)->connection();
    $table = 'fulcrum_integration_' . bin2hex(random_bytes(6));
    $idColumn = $driver === 'pgsql'
        ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
        : 'BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY';

    $db->statement("CREATE TABLE {$table} (id {$idColumn}, name VARCHAR(255) NOT NULL)");

    try {
        $id = $db->table($table)->insert(['name' => 'Ada']);
        $row = $db->table($table)->where('id', $id)->first();

        expect($row)->toBeArray()
            ->and($row['name'] ?? null)->toBe('Ada');
    } finally {
        $db->statement("DROP TABLE IF EXISTS {$table}");
    }
}

function exerciseTransactionBehavior(string $driver): void
{
    $db = relationalDatabase($driver)->connection();
    $table = 'fulcrum_tx_' . bin2hex(random_bytes(6));
    $idColumn = $driver === 'pgsql'
        ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
        : 'BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY';
    $afterCommitCalls = 0;

    $db->statement("CREATE TABLE {$table} (id {$idColumn}, name VARCHAR(255) NOT NULL)");

    try {
        $db->transaction(function () use ($db, $table, &$afterCommitCalls): void {
            $db->table($table)->insert(['name' => 'committed']);
            $db->afterCommit(function () use (&$afterCommitCalls): void {
                $afterCommitCalls++;
            });
        });

        expect($afterCommitCalls)->toBe(1)
            ->and($db->table($table)->where('name', 'committed')->first())->toBeArray();

        try {
            $db->transaction(function () use ($db, $table): void {
                $db->table($table)->insert(['name' => 'rolled_back']);

                throw new RuntimeException('rollback probe');
            });
        } catch (RuntimeException $exception) {
            expect($exception->getMessage())->toBe('rollback probe');
        }

        expect($db->table($table)->where('name', 'rolled_back')->first())->toBeNull();
    } finally {
        $db->statement("DROP TABLE IF EXISTS {$table}");
    }
}

/** @return list<string> */
function migrationTables(): array
{
    return [
        'migrations',
        'model_permissions',
        'model_roles',
        'role_permissions',
        'permissions',
        'roles',
        'personal_access_tokens',
        'subscription_events',
        'failed_jobs',
        'idempotency_keys',
        'jobs',
        'users',
    ];
}

function dropMigrationTables(ConnectionInterface $db): void
{
    foreach (migrationTables() as $table) {
        $db->statement("DROP TABLE IF EXISTS {$table}");
    }
}

function tableExists(ConnectionInterface $db, string $table): bool
{
    if ($db instanceof PostgresDriver) {
        return $db->select(
            'SELECT table_name FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = ?',
            [$table]
        )->first() !== null;
    }

    return $db->select(
        'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?',
        [$table]
    )->first() !== null;
}

/**
 * @param callable(DatabaseManager): void $callback
 */
function withMigrationSandbox(string $driver, callable $callback): void
{
    $manager = relationalDatabase($driver);
    $connection = $manager->connection();

    if ($connection instanceof PostgresDriver) {
        $schema = 'fulcrum_integration_' . bin2hex(random_bytes(6));
        $connection->statement("CREATE SCHEMA {$schema}");
        $connection->statement("SET search_path TO {$schema}");

        try {
            $callback($manager);
        } finally {
            $connection->statement('SET search_path TO public');
            $connection->statement("DROP SCHEMA IF EXISTS {$schema} CASCADE");
        }

        return;
    }

    dropMigrationTables($connection);

    try {
        $callback($manager);
    } finally {
        dropMigrationTables($connection);
    }
}

/**
 * @param list<string> $expectedTables
 */
function exerciseMigrationPath(string $driver, string $path, array $expectedTables): void
{
    withMigrationSandbox($driver, function (DatabaseManager $manager) use ($path, $expectedTables): void {
        $migrator = new Migrator(new MigrationRepository($manager));
        $ran = $migrator->run($path);

        expect($ran)->not->toBeEmpty();

        foreach ($expectedTables as $table) {
            expect(tableExists($manager->connection(), $table))->toBeTrue("Expected table [{$table}] to exist.");
        }

        $status = $migrator->status($path);
        expect($status)->not->toBeEmpty();

        foreach ($status as $row) {
            expect($row['ran'])->toBeTrue("Expected migration [{$row['migration']}] to be marked as ran.");
        }

        $rolledBack = $migrator->rollback($path);
        expect($rolledBack)->toHaveCount(count($ran));

        foreach ($expectedTables as $table) {
            expect(tableExists($manager->connection(), $table))->toBeFalse("Expected table [{$table}] to be rolled back.");
        }
    });
}

function exerciseDatabaseQueue(string $driver): void
{
    withMigrationSandbox($driver, function (DatabaseManager $manager): void {
        $migrator = new Migrator(new MigrationRepository($manager));
        $migrator->run(__DIR__ . '/../../src/Fulcrum/Queue/Migrations');

        $queue = new DatabaseQueue($manager, 'jobs', 'integration', 'failed_jobs', 1);
        $queue->push(new IntegrationProbeJob('first'));

        expect($queue->size())->toBe(1);

        $firstClaim = $queue->pop();
        expect($firstClaim)->not->toBeNull()
            ->and($firstClaim?->attempts)->toBe(1)
            ->and($firstClaim?->job)->toBeInstanceOf(IntegrationProbeJob::class)
            ->and($queue->pop())->toBeNull();

        if ($firstClaim === null) {
            return;
        }

        $queue->release($firstClaim, 0);

        $secondClaim = $queue->pop();
        expect($secondClaim)->not->toBeNull()
            ->and($secondClaim?->id)->toBe($firstClaim->id)
            ->and($secondClaim?->attempts)->toBe(2);

        if ($secondClaim === null) {
            return;
        }

        $queue->fail($secondClaim, new RuntimeException('failed intentionally'));

        expect($queue->size())->toBe(0)
            ->and($queue->failedCount())->toBe(1);
    });
}

it('connects to a real PostgreSQL database', function () {
    if (getenv('FULCRUM_TEST_PGSQL') !== '1') {
        $this->markTestSkipped('Set FULCRUM_TEST_PGSQL=1 to run PostgreSQL integration tests.');
    }

    exerciseRelationalDatabase('pgsql');
});

it('connects to a real MySQL database', function () {
    if (getenv('FULCRUM_TEST_MYSQL') !== '1') {
        $this->markTestSkipped('Set FULCRUM_TEST_MYSQL=1 to run MySQL integration tests.');
    }

    exerciseRelationalDatabase('mysql');
});

it('connects to a real Redis cache', function () {
    if (getenv('FULCRUM_TEST_REDIS') !== '1') {
        $this->markTestSkipped('Set FULCRUM_TEST_REDIS=1 to run Redis integration tests.');
    }

    $config = integrationConfig();
    $config->set('cache.default', 'redis');
    $config->set('cache.stores.redis', [
        'driver' => 'redis',
        'host' => envString('FULCRUM_REDIS_HOST', '127.0.0.1'),
        'port' => envInt('FULCRUM_REDIS_PORT', 6379),
        'database' => envInt('FULCRUM_REDIS_DATABASE', 0),
        'prefix' => 'fulcrum:integration:',
    ]);

    $cache = (new CacheManager($config))->store();
    $key = 'probe:' . bin2hex(random_bytes(6));

    try {
        $cache->put($key, 'ok', 30);

        expect($cache->get($key))->toBe('ok')
            ->and($cache->increment($key . ':count', 2, 30))->toBe(2);
    } finally {
        $cache->forget($key);
        $cache->forget($key . ':count');
    }
});

it('commits and rolls back transactions on PostgreSQL', function () {
    if (getenv('FULCRUM_TEST_PGSQL') !== '1') {
        $this->markTestSkipped('Set FULCRUM_TEST_PGSQL=1 to run PostgreSQL integration tests.');
    }

    exerciseTransactionBehavior('pgsql');
});

it('commits and rolls back transactions on MySQL', function () {
    if (getenv('FULCRUM_TEST_MYSQL') !== '1') {
        $this->markTestSkipped('Set FULCRUM_TEST_MYSQL=1 to run MySQL integration tests.');
    }

    exerciseTransactionBehavior('mysql');
});

it('runs and rolls back skeleton migrations on PostgreSQL', function () {
    if (getenv('FULCRUM_TEST_PGSQL') !== '1') {
        $this->markTestSkipped('Set FULCRUM_TEST_PGSQL=1 to run PostgreSQL integration tests.');
    }

    if (! migrationIntegrationTestsEnabled()) {
        $this->markTestSkipped('Set FULCRUM_TEST_MIGRATIONS=1 to run migration integration tests.');
    }

    exerciseMigrationPath('pgsql', __DIR__ . '/../../../skeleton/database/migrations', [
        'users',
        'jobs',
        'idempotency_keys',
        'failed_jobs',
        'subscription_events',
        'personal_access_tokens',
        'roles',
        'permissions',
        'role_permissions',
        'model_roles',
        'model_permissions',
    ]);
});

it('runs and rolls back skeleton migrations on MySQL', function () {
    if (getenv('FULCRUM_TEST_MYSQL') !== '1') {
        $this->markTestSkipped('Set FULCRUM_TEST_MYSQL=1 to run MySQL integration tests.');
    }

    if (! migrationIntegrationTestsEnabled()) {
        $this->markTestSkipped('Set FULCRUM_TEST_MIGRATIONS=1 to run migration integration tests.');
    }

    exerciseMigrationPath('mysql', __DIR__ . '/../../../skeleton/database/migrations', [
        'users',
        'jobs',
        'idempotency_keys',
        'failed_jobs',
        'subscription_events',
        'personal_access_tokens',
        'roles',
        'permissions',
        'role_permissions',
        'model_roles',
        'model_permissions',
    ]);
});

it('runs and rolls back package auth and queue migrations on PostgreSQL', function () {
    if (getenv('FULCRUM_TEST_PGSQL') !== '1') {
        $this->markTestSkipped('Set FULCRUM_TEST_PGSQL=1 to run PostgreSQL integration tests.');
    }

    if (! migrationIntegrationTestsEnabled()) {
        $this->markTestSkipped('Set FULCRUM_TEST_MIGRATIONS=1 to run migration integration tests.');
    }

    exerciseMigrationPath('pgsql', __DIR__ . '/../../src/Fulcrum/Queue/Migrations', [
        'jobs',
        'failed_jobs',
    ]);

    exerciseMigrationPath('pgsql', __DIR__ . '/../../src/Fulcrum/Auth/Migrations', [
        'personal_access_tokens',
        'roles',
        'permissions',
        'role_permissions',
        'model_roles',
        'model_permissions',
    ]);
});

it('runs and rolls back package auth and queue migrations on MySQL', function () {
    if (getenv('FULCRUM_TEST_MYSQL') !== '1') {
        $this->markTestSkipped('Set FULCRUM_TEST_MYSQL=1 to run MySQL integration tests.');
    }

    if (! migrationIntegrationTestsEnabled()) {
        $this->markTestSkipped('Set FULCRUM_TEST_MIGRATIONS=1 to run migration integration tests.');
    }

    exerciseMigrationPath('mysql', __DIR__ . '/../../src/Fulcrum/Queue/Migrations', [
        'jobs',
        'failed_jobs',
    ]);

    exerciseMigrationPath('mysql', __DIR__ . '/../../src/Fulcrum/Auth/Migrations', [
        'personal_access_tokens',
        'roles',
        'permissions',
        'role_permissions',
        'model_roles',
        'model_permissions',
    ]);
});

it('reserves releases and fails database queued jobs on PostgreSQL', function () {
    if (getenv('FULCRUM_TEST_PGSQL') !== '1') {
        $this->markTestSkipped('Set FULCRUM_TEST_PGSQL=1 to run PostgreSQL integration tests.');
    }

    if (! migrationIntegrationTestsEnabled()) {
        $this->markTestSkipped('Set FULCRUM_TEST_MIGRATIONS=1 to run migration integration tests.');
    }

    exerciseDatabaseQueue('pgsql');
});

it('reserves releases and fails database queued jobs on MySQL', function () {
    if (getenv('FULCRUM_TEST_MYSQL') !== '1') {
        $this->markTestSkipped('Set FULCRUM_TEST_MYSQL=1 to run MySQL integration tests.');
    }

    if (! migrationIntegrationTestsEnabled()) {
        $this->markTestSkipped('Set FULCRUM_TEST_MIGRATIONS=1 to run migration integration tests.');
    }

    exerciseDatabaseQueue('mysql');
});
