<?php

declare(strict_types=1);

use Fulcrum\Database\ConnectionInterface;
use Fulcrum\Database\Drivers\PostgresDriver;
use Fulcrum\Database\Migrations\Migration;

return new class implements Migration {
    public function up(ConnectionInterface $db): void
    {
        if ($db instanceof PostgresDriver) {
            $db->statement(
                'CREATE TABLE IF NOT EXISTS failed_jobs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    job_id VARCHAR(255) NOT NULL,
                    queue VARCHAR(255) NOT NULL,
                    payload TEXT NOT NULL,
                    exception TEXT NOT NULL,
                    attempts INTEGER NOT NULL DEFAULT 0,
                    failed_at INTEGER NOT NULL
                )'
            );
            $db->statement('CREATE INDEX IF NOT EXISTS failed_jobs_queue_failed_at_index ON failed_jobs (queue, failed_at)');

            return;
        }

        $db->statement(
            'CREATE TABLE IF NOT EXISTS failed_jobs (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                job_id VARCHAR(255) NOT NULL,
                queue VARCHAR(255) NOT NULL,
                payload LONGTEXT NOT NULL,
                exception LONGTEXT NOT NULL,
                attempts INT UNSIGNED NOT NULL DEFAULT 0,
                failed_at INT NOT NULL,
                PRIMARY KEY (id),
                KEY failed_jobs_queue_failed_at_index (queue, failed_at)
            )'
        );
    }

    public function down(ConnectionInterface $db): void
    {
        $db->statement('DROP TABLE IF EXISTS failed_jobs');
    }
};
