<?php

declare(strict_types=1);

use Fulcrum\Database\ConnectionInterface;
use Fulcrum\Database\Drivers\PostgresDriver;
use Fulcrum\Database\Migrations\Migration;

return new class implements Migration {
    public function up(ConnectionInterface $db): void
    {
        if ($db instanceof PostgresDriver) {
            $db->statement(
                'CREATE TABLE IF NOT EXISTS personal_access_tokens (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tokenable_type VARCHAR(255) NOT NULL,
                    tokenable_id VARCHAR(255) NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    token VARCHAR(64) NOT NULL,
                    abilities TEXT NULL,
                    last_used_at TIMESTAMP NULL DEFAULT NULL,
                    expires_at TIMESTAMP NULL DEFAULT NULL,
                    created_at TIMESTAMP NULL DEFAULT NULL,
                    updated_at TIMESTAMP NULL DEFAULT NULL,
                    CONSTRAINT personal_access_tokens_token_unique UNIQUE (token)
                )'
            );
            $db->statement('CREATE INDEX IF NOT EXISTS personal_access_tokens_tokenable_index ON personal_access_tokens (tokenable_type, tokenable_id)');

            return;
        }

        $db->statement(
            'CREATE TABLE IF NOT EXISTS personal_access_tokens (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                tokenable_type VARCHAR(255) NOT NULL,
                tokenable_id VARCHAR(255) NOT NULL,
                name VARCHAR(255) NOT NULL,
                token VARCHAR(64) NOT NULL,
                abilities TEXT NULL,
                last_used_at TIMESTAMP NULL DEFAULT NULL,
                expires_at TIMESTAMP NULL DEFAULT NULL,
                created_at TIMESTAMP NULL DEFAULT NULL,
                updated_at TIMESTAMP NULL DEFAULT NULL,
                PRIMARY KEY (id),
                UNIQUE KEY personal_access_tokens_token_unique (token),
                KEY personal_access_tokens_tokenable_index (tokenable_type, tokenable_id)
            )'
        );
    }

    public function down(ConnectionInterface $db): void
    {
        $db->statement('DROP TABLE IF EXISTS personal_access_tokens');
    }
};
