<?php

declare(strict_types=1);

use Fulcrum\Database\ConnectionInterface;
use Fulcrum\Database\Drivers\PostgresDriver;
use Fulcrum\Database\Migrations\SchemaSupport;
use Fulcrum\Database\QueryBuilder;
use Fulcrum\Support\Collection;

final class SchemaSupportTestConnection implements ConnectionInterface
{
    /** @var list<string> */
    public array $statements = [];

    public bool $indexExists = false;

    public function beginTransaction(): void {}

    public function commit(): void {}

    public function rollBack(): void {}

    public function transactionLevel(): int
    {
        return 0;
    }

    public function transaction(callable $callback): mixed
    {
        return $callback();
    }

    public function afterCommit(callable $callback): void
    {
        $callback();
    }

    public function table(string $table): QueryBuilder
    {
        throw new RuntimeException('Query builder is not needed for schema support tests.');
    }

    /**
     * @param array<mixed> $bindings
     * @return Collection<array<string, mixed>>
     */
    public function select(string $query, array $bindings = []): Collection
    {
        return new Collection($this->indexRows($bindings));
    }

    public function insert(string $query, array $bindings = []): int|string
    {
        return $this->indexExists ? '0' : 0;
    }

    public function update(string $query, array $bindings = []): int
    {
        return 0;
    }

    public function delete(string $query, array $bindings = []): int
    {
        return 0;
    }

    public function statement(string $query, array $bindings = []): bool
    {
        $this->statements[] = $query;

        return true;
    }

    /**
     * @param array<mixed> $bindings
     * @return list<array<string, mixed>>
     */
    private function indexRows(array $bindings): array
    {
        if (!$this->indexExists) {
            return [];
        }

        return [
            ['INDEX_NAME' => is_string($bindings[1] ?? null) ? $bindings[1] : 'test_index'],
        ];
    }
}

it('provides portable schema type fragments for mysql style connections', function () {
    $db = new SchemaSupportTestConnection();

    expect(SchemaSupport::bigIncrements($db))->toBe('BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY')
        ->and(SchemaSupport::bigInteger($db))->toBe('BIGINT UNSIGNED')
        ->and(SchemaSupport::integer($db))->toBe('INT')
        ->and(SchemaSupport::unsignedInteger($db))->toBe('INT UNSIGNED')
        ->and(SchemaSupport::nullableTimestamp())->toBe('TIMESTAMP NULL DEFAULT NULL');
});

it('provides portable schema type fragments for postgres connections', function () {
    $db = new PostgresDriver(new PDO('sqlite::memory:'));

    expect(SchemaSupport::isPostgres($db))->toBeTrue()
        ->and(SchemaSupport::bigIncrements($db))->toBe('BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        ->and(SchemaSupport::bigInteger($db))->toBe('BIGINT')
        ->and(SchemaSupport::integer($db))->toBe('INTEGER')
        ->and(SchemaSupport::unsignedInteger($db))->toBe('INTEGER');
});

it('creates mysql style indexes only when missing', function () {
    $db = new SchemaSupportTestConnection();

    SchemaSupport::createIndex($db, 'users', 'users_email_index', ['email'], unique: true);

    expect($db->statements)->toBe(['ALTER TABLE users ADD UNIQUE INDEX users_email_index (email)']);

    $db->indexExists = true;
    SchemaSupport::createIndex($db, 'users', 'users_email_index', ['email'], unique: true);

    expect($db->statements)->toHaveCount(1);
});
