<?php

declare(strict_types=1);

namespace Fulcrum\Database\Migrations;

use Fulcrum\Database\ConnectionInterface;
use Fulcrum\Database\Drivers\PostgresDriver;

final class SchemaSupport
{
    public static function isPostgres(ConnectionInterface $db): bool
    {
        return $db instanceof PostgresDriver;
    }

    public static function bigIncrements(ConnectionInterface $db): string
    {
        return self::isPostgres($db)
            ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
            : 'BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY';
    }

    public static function integer(ConnectionInterface $db): string
    {
        return self::isPostgres($db) ? 'INTEGER' : 'INT';
    }

    public static function unsignedInteger(ConnectionInterface $db): string
    {
        return self::isPostgres($db) ? 'INTEGER' : 'INT UNSIGNED';
    }

    public static function bigInteger(ConnectionInterface $db): string
    {
        return self::isPostgres($db) ? 'BIGINT' : 'BIGINT UNSIGNED';
    }

    public static function nullableTimestamp(): string
    {
        return 'TIMESTAMP NULL DEFAULT NULL';
    }

    /**
     * @param list<string> $columns
     */
    public static function createIndex(ConnectionInterface $db, string $table, string $name, array $columns, bool $unique = false): void
    {
        $columnList = implode(', ', $columns);

        if (self::isPostgres($db)) {
            $uniqueSql = $unique ? 'UNIQUE ' : '';
            $db->statement("CREATE {$uniqueSql}INDEX IF NOT EXISTS {$name} ON {$table} ({$columnList})");

            return;
        }

        if (self::hasIndex($db, $table, $name)) {
            return;
        }

        $uniqueSql = $unique ? 'UNIQUE ' : '';
        $db->statement("ALTER TABLE {$table} ADD {$uniqueSql}INDEX {$name} ({$columnList})");
    }

    public static function hasIndex(ConnectionInterface $db, string $table, string $name): bool
    {
        if (self::isPostgres($db)) {
            return $db->select(
                'SELECT indexname FROM pg_indexes WHERE schemaname = current_schema() AND tablename = ? AND indexname = ?',
                [$table, $name]
            )->first() !== null;
        }

        return $db->select(
            'SELECT INDEX_NAME FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND INDEX_NAME = ?',
            [$table, $name]
        )->first() !== null;
    }
}
